apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionString: "Server=mssql-service,1433;Database=CurrencyWalletDb;User Id=sa;Password={PASSWORD};TrustServerCertificate=True;"